### ISSUE TITLE
STOW, uma ferramenta GNU para gerenciamento de dotfiles

### ISSUE THREAD

**Issue by Gabriel-Goes** [leouieda/dotfiles#9]
Uma issue que na verdade é um pull request. Ainda to aprendendo a usar git.

# DOTFILES

## Descrição 
Este repositório contém arquivos de configuração do ambiete de trabalo, além
de scripts para instalação e configuração do ambiente com git e stow.

## Uso
```bash
./install.sh
```

################################
#!/bin/bash
# Descrição : Script de instalação dos dotfiles

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty bin i3 nvim obs-studio picom tmux"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

################################
#!/bin/bash
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS)
do
    mkdir -p $HOME/.config/$folder
    echo "stow $folder"
    stow -D $folder
    stow -t $HOME/.config/$folder $folder
done
popd

https://github.com/Gabriel-Goes/.dotfiles

**Comment by leouieda** [comment]
Já tinham me recomendado usar o `stow` mas tinha esquecido. Acabei de implementar e achei bem fácil!

**Comment by Gabriel-Goes** [comment]
eu fiquei com receio porque depois que eu fui reparar que já havia um código makefile que realizava um comando parecido com cp -r... mas o stow é um pouco mais, ele gerencia links simbólicos.
